INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)VALUES(101,'HCL',700.25);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)VALUES(102,'INFOSYS',950.25);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)VALUES(103,'BHEL',40.35);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)VALUES(104,'IOC',90.15);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)VALUES(105,'TCS',500.25);
